# Generated by Django 3.0.6 on 2020-05-16 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NazwaTowaru',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_towar', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Sklep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_sklep', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PozycjaZakupowa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ilosc', models.IntegerField(default=0)),
                ('cena', models.FloatField(default=0.0)),
                ('nazwa_sklep', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Sklep')),
                ('nazwa_towar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.NazwaTowaru')),
            ],
        ),
    ]
